# Generated by Django 5.1.2 on 2024-10-25 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('losb', '0001_initial'), ('losb', '0002_remove_user_last_login_remove_user_last_loginnn'), ('losb', '0003_alter_phone_phone'), ('losb', '0004_user_city_alter_user_phone'), ('losb', '0005_alter_user_bday'), ('losb', '0006_alter_user_password'), ('losb', '0007_alter_user_password'), ('losb', '0008_alter_user_bday'), ('losb', '0009_alter_user_bday'), ('losb', '0010_alter_user_bday'), ('losb', '0011_alter_user_bday'), ('losb', '0012_alter_user_bday'), ('losb', '0013_alter_user_bday'), ('losb', '0014_phone_vc_created_at_phone_verification_code'), ('losb', '0015_verificationcode_remove_phone_vc_created_at_and_more'), ('losb', '0016_smsverification_remove_user_verification_code_and_more'), ('losb', '0017_alter_user_phone_alter_user_sms_verification'), ('losb', '0018_alter_smsverification_attempts'), ('losb', '0019_alter_phone_code_alter_phone_phone'), ('losb', '0020_rename_phone_phone_number_and_more'), ('losb', '0021_alter_user_sms_verification'), ('losb', '0022_rename_bday_user_birthday_rename_city_user_location'), ('losb', '0023_rename_avatar_user_avatar_url')]

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField()),
                ('number', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SmsVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=4)),
                ('attempts', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=255, unique=True)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('avatar_url', models.ImageField(blank=True, max_length=512, null=True, upload_to='user/avatar/', verbose_name='Аватар')),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('birthday', models.DateField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='losb.phone')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to='losb.city')),
                ('sms_verification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='losb.smsverification')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
