# Generated by Django 5.1.2 on 2024-10-16 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('losb', '0003_alter_phone_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to='losb.city'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to='losb.phone'),
        ),
    ]
