# Generated by Django 5.1.2 on 2024-10-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('losb', '0004_user_city_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bday',
            field=models.DateTimeField(null=True),
        ),
    ]
