# Generated by Django 5.1.2 on 2024-10-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('losb', '0006_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
