# Generated by Django 5.1.2 on 2024-10-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('losb', '0010_alter_user_bday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bday',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
