# Generated by Django 5.1.2 on 2024-10-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('losb', '0012_alter_user_bday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bday',
            field=models.DateField(default=None, null=True),
        ),
    ]
