# Generated by Django 5.1.2 on 2024-10-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('losb', '0013_alter_user_bday'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='vc_created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='verification_code',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
