# Generated by Django 5.1.2 on 2024-10-24 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('losb', '0014_phone_vc_created_at_phone_verification_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('attempts', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='phone',
            name='vc_created_at',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='verification_code',
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to='losb.verificationcode'),
        ),
    ]
