# Generated by Django 5.1.2 on 2024-10-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('losb', '0017_alter_user_phone_alter_user_sms_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsverification',
            name='attempts',
            field=models.SmallIntegerField(default=0),
        ),
    ]
