# Generated by Django 5.1.2 on 2024-10-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('losb', '0018_alter_smsverification_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='code',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone',
            field=models.CharField(blank=True, null=True),
        ),
    ]
