# Generated by Django 5.1.2 on 2024-10-25 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('losb', '0019_alter_phone_code_alter_phone_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='phone',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='smsverification',
            old_name='code',
            new_name='otp',
        ),
    ]
