# Generated by Django 5.1.2 on 2024-10-25 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('losb', '0021_alter_user_sms_verification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bday',
            new_name='birthday',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='city',
            new_name='location',
        ),
    ]
