# Generated by Django 5.1.2 on 2024-10-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('losb', '0001_squashed_0023_rename_avatar_user_avatar_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='full_name',
        ),
        migrations.AlterField(
            model_name='smsverification',
            name='otp',
            field=models.CharField(max_length=6),
        ),
    ]
