# Generated by Django 5.1.2 on 2024-11-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('losb', '0024_rename_name_user_full_name_alter_smsverification_otp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterField(
            model_name='phone',
            name='code',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
