# Generated by Django 5.1.2 on 2024-11-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('losb', '0025_alter_city_options_alter_phone_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
